apiVersion: v1
kind: Service
metadata:
  name: podman-openshift
  namespace: romanyuvan-dev
spec:
  selector:
    app: podman-openshift
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
